# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPhA_SeBXjbtklCoEMSer6QfqnKRDD3R
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from scipy.stats import f_oneway, pearsonr

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')

print("Dataset loaded successfully!")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

df.info()

display(df.describe().T)

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print(f"\n===== {col} =====")
    print(df[col].value_counts())

missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

missing_table = pd.DataFrame({
    'Missing Values': missing,
    'Missing Percentage': missing_percentage
})

display(missing_table[missing_table['Missing Values'] > 0])

duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

unique_table = pd.DataFrame({
    'Column': df.columns,
    'Unique Values': [df[col].nunique() for col in df.columns]
})

display(unique_table)

df_clean = df.copy()


numeric_columns = df_clean.select_dtypes(include=np.number).columns


for col in numeric_columns:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col] = df_clean[col].fillna(df_clean[col].median())

df_clean = df_clean.drop_duplicates()

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_clean.shape)

print("\nRemaining missing values:")
print(df_clean.isnull().sum().sum())

print("Missing values after cleaning:")
display(df_clean.isnull().sum())

print("\nDuplicate rows after cleaning:")
print(df_clean.duplicated().sum())

print("Seasons available:")
print(df_clean['Season'].value_counts())

plt.figure(figsize=(8,5))

sns.countplot(data=df_clean, x='Season')

plt.title('Number of Agricultural Records by Season')
plt.xlabel('Season')
plt.ylabel('Number of Records')

plt.show()

season_summary = df_clean.groupby('Season').agg({

    'Yield_Tonnes_Ha': 'mean',
    'Production_Tonnes': 'mean',
    'Revenue_INR': 'mean',
    'Total_Cost_INR': 'mean',
    'Profit_INR': 'mean',
    'Water_Used_m3': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean',
    'Disease_Pest_Risk_pct': 'mean'

}).round(2)

display(season_summary)

yield_by_season = df_clean.groupby('Season')['Yield_Tonnes_Ha'].mean().sort_values(
    ascending=False
)

print("Average Yield by Season:")
display(yield_by_season)

plt.figure(figsize=(8,5))

sns.barplot(
    data=df_clean,
    x='Season',
    y='Yield_Tonnes_Ha',
    estimator='mean'
)

plt.title('Average Agricultural Yield by Season')
plt.xlabel('Season')
plt.ylabel('Average Yield (Tonnes/Ha)')

plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    data=df_clean,
    x='Season',
    y='Yield_Tonnes_Ha'
)

plt.title('Yield Distribution Across Seasons')
plt.xlabel('Season')
plt.ylabel('Yield (Tonnes/Ha)')

plt.show()

production = df_clean.groupby('Season')['Production_Tonnes'].mean().sort_values(
    ascending=False
)

display(production)

plt.figure(figsize=(8,5))

sns.barplot(
    data=df_clean,
    x='Season',
    y='Production_Tonnes',
    estimator='mean'
)

plt.title('Average Production by Season')
plt.xlabel('Season')
plt.ylabel('Production (Tonnes)')

plt.show()

economic_summary = df_clean.groupby('Season').agg({
    'Market_Price_INR_Tonne': 'mean',
    'Total_Cost_INR': 'mean',
    'Revenue_INR': 'mean',
    'Profit_INR': 'mean'
}).round(2)

display(economic_summary)

plt.figure(figsize=(8,5))

sns.barplot(
    data=df_clean,
    x='Season',
    y='Profit_INR',
    estimator='mean'
)

plt.title('Average Profit by Season')
plt.xlabel('Season')
plt.ylabel('Average Profit (INR)')

plt.show()

revenue_cost = df_clean.groupby('Season').agg({
    'Revenue_INR': 'mean',
    'Total_Cost_INR': 'mean'
})

display(revenue_cost)

revenue_cost.plot(
    kind='bar',
    figsize=(10,6)
)

plt.title('Average Revenue and Cost by Season')
plt.xlabel('Season')
plt.ylabel('INR')

plt.xticks(rotation=0)
plt.legend(title='Financial Measure')

plt.show()

resource_summary = df_clean.groupby('Season').agg({

    'Fertilizer_kg_ha': 'mean',
    'Pesticide_Litre_ha': 'mean',
    'Water_Used_m3': 'mean',
    'Nitrogen_kg_ha': 'mean',
    'Phosphorus_kg_ha': 'mean',
    'Potassium_kg_ha': 'mean'

}).round(2)

display(resource_summary)

-

plt.figure(figsize=(8,5))

sns.barplot(
    data=df_clean,
    x='Season',
    y='Water_Efficiency_t_per_1000m3',
    estimator='mean'
)

plt.title('Average Water Efficiency by Season')
plt.xlabel('Season')
plt.ylabel('Tonnes per 1,000 m³')

plt.show()

environment_summary = df_clean.groupby('Season').agg({

    'Rainfall_mm': 'mean',
    'Avg_Temperature_C': 'mean',
    'Humidity_pct': 'mean',
    'Sunlight_Hours_Day': 'mean',
    'Soil_Moisture_pct': 'mean',
    'Soil_pH': 'mean'

}).round(2)

display(environment_summary)

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df_clean,
    x='Season',
    y='Rainfall_mm'
)

plt.title('Rainfall Distribution Across Seasons')
plt.xlabel('Season')
plt.ylabel('Rainfall (mm)')

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df_clean,
    x='Season',
    y='Avg_Temperature_C'
)

plt.title('Temperature Distribution Across Seasons')
plt.xlabel('Season')
plt.ylabel('Average Temperature (°C)')

plt.show()

-

crop_season_summary = df_clean.groupby(
    ['Season', 'Crop']
)['Yield_Tonnes_Ha'].mean().reset_index()

display(
    crop_season_summary.sort_values(
        'Yield_Tonnes_Ha',
        ascending=False
    ).head(20)
)

crop_season_pivot = df_clean.pivot_table(
    index='Crop',
    columns='Season',
    values='Yield_Tonnes_Ha',
    aggfunc='mean'
)

plt.figure(figsize=(10,7))

sns.heatmap(
    crop_season_pivot,
    annot=True,
    fmt='.2f'
)

plt.title('Average Yield by Crop and Season')
plt.xlabel('Season')
plt.ylabel('Crop')

plt.show()

irrigation_summary = df_clean.groupby(
    ['Season', 'Irrigation_Method']
).agg({

    'Yield_Tonnes_Ha': 'mean',
    'Profit_INR': 'mean',
    'Water_Used_m3': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean'

}).round(2)

display(irrigation_summary)

plt.figure(figsize=(10,6))

sns.barplot(
    data=df_clean,
    x='Irrigation_Method',
    y='Yield_Tonnes_Ha',
    hue='Season',
    estimator='mean'
)

plt.title('Average Yield by Irrigation Method and Season')
plt.xlabel('Irrigation Method')
plt.ylabel('Yield (Tonnes/Ha)')

plt.show()

state_summary = df_clean.groupby('State').agg({

    'Yield_Tonnes_Ha': 'mean',
    'Production_Tonnes': 'mean',
    'Revenue_INR': 'mean',
    'Profit_INR': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean'

}).round(2)

display(state_summary.sort_values(
    'Yield_Tonnes_Ha',
    ascending=False
))

state_season = df_clean.pivot_table(
    index='State',
    columns='Season',
    values='Yield_Tonnes_Ha',
    aggfunc='mean'
)

display(state_season)

plt.figure(figsize=(12,8))

sns.heatmap(
    state_season,
    annot=True,
    fmt='.2f'
)

plt.title('Average Yield by State and Season')
plt.xlabel('Season')
plt.ylabel('State')

plt.show()

numeric_df = df_clean.select_dtypes(include=np.number)

correlation = numeric_df.corr()

plt.figure(figsize=(16,12))

sns.heatmap(
    correlation,
    cmap='coolwarm',
    center=0
)

plt.title('Correlation Matrix of Agricultural Variables')

plt.show()

yield_corr = correlation['Yield_Tonnes_Ha'].sort_values(
    ascending=False
)

display(yield_corr)

print("Strongest negative correlations with yield:")

display(
    yield_corr.sort_values().head(10)
)

plt.figure(figsize=(9,6))

sns.scatterplot(
    data=df_clean,
    x='Rainfall_mm',
    y='Yield_Tonnes_Ha',
    hue='Season'
)

plt.title('Rainfall vs Agricultural Yield')
plt.xlabel('Rainfall (mm)')
plt.ylabel('Yield (Tonnes/Ha)')

plt.show()

plt.figure(figsize=(9,6))

sns.scatterplot(
    data=df_clean,
    x='Avg_Temperature_C',
    y='Yield_Tonnes_Ha',
    hue='Season'
)

plt.title('Temperature vs Agricultural Yield')
plt.xlabel('Average Temperature (°C)')
plt.ylabel('Yield (Tonnes/Ha)')

plt.show()

plt.figure(figsize=(9,6))

sns.scatterplot(
    data=df_clean,
    x='Disease_Pest_Risk_pct',
    y='Yield_Tonnes_Ha',
    hue='Season'
)

plt.title('Disease/Pest Risk vs Agricultural Yield')
plt.xlabel('Disease/Pest Risk (%)')
plt.ylabel('Yield (Tonnes/Ha)')

plt.show()

seasons = df_clean['Season'].unique()

season_groups = [
    df_clean[df_clean['Season'] == season]['Yield_Tonnes_Ha']
    for season in seasons
]

anova_stat, p_value = f_oneway(*season_groups)

print("ANOVA F-statistic:", anova_stat)
print("ANOVA p-value:", p_value)

alpha = 0.05

if p_value < alpha:
    print("\nResult: Yield differs significantly across seasons.")
else:
    print("\nResult: No statistically significant difference in yield across seasons.")

r, p = pearsonr(
    df_clean['Rainfall_mm'],
    df_clean['Yield_Tonnes_Ha']
)

print("Pearson correlation coefficient:", r)
print("p-value:", p)

if p < 0.05:
    print("The relationship is statistically significant.")
else:
    print("The relationship is not statistically significant.")

r, p = pearsonr(
    df_clean['Avg_Temperature_C'],
    df_clean['Yield_Tonnes_Ha']
)

print("Correlation coefficient:", r)
print("p-value:", p)

r, p = pearsonr(
    df_clean['Water_Used_m3'],
    df_clean['Yield_Tonnes_Ha']
)

print("Correlation coefficient:", r)
print("p-value:", p)

Q1 = df_clean['Yield_Tonnes_Ha'].quantile(0.25)
Q3 = df_clean['Yield_Tonnes_Ha'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df_clean[
    (df_clean['Yield_Tonnes_Ha'] < lower_bound) |
    (df_clean['Yield_Tonnes_Ha'] > upper_bound)
]

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of yield outliers:", len(outliers))

display(outliers.head(20))

season_variability = df_clean.groupby('Season').agg({

    'Yield_Tonnes_Ha': ['mean', 'std', 'min', 'max'],
    'Profit_INR': ['mean', 'std'],
    'Water_Used_m3': ['mean', 'std']

}).round(2)

display(season_variability)

score_data = df_clean[
    ['Yield_Tonnes_Ha',
     'Profit_INR',
     'Water_Efficiency_t_per_1000m3']
].copy()

scaler = StandardScaler()

score_data_scaled = scaler.fit_transform(score_data)

df_clean['Performance_Score'] = score_data_scaled.mean(axis=1)

season_score = df_clean.groupby(
    'Season'
)['Performance_Score'].mean().sort_values(
    ascending=False
)

display(season_score)

plt.figure(figsize=(8,5))

sns.barplot(
    x=season_score.index,
    y=season_score.values
)

plt.title('Average Agricultural Performance Score by Season')
plt.xlabel('Season')
plt.ylabel('Performance Score')

plt.show()

ml_df = df_clean.copy()


ml_df = ml_df.drop(columns=['Farm_ID'])


ml_df = pd.get_dummies(
    ml_df,
    columns=['State', 'District', 'Crop', 'Season', 'Irrigation_Method'],
    drop_first=True
)

print("ML dataset shape:", ml_df.shape)

X = ml_df.drop(columns=['Yield_Tonnes_Ha'])
y = ml_df['Yield_Tonnes_Ha']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("Model trained successfully!")

mae = mean_absolute_error(y_test, predictions)

rmse = np.sqrt(
    mean_squared_error(y_test, predictions)
)

r2 = r2_score(y_test, predictions)

print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)
print("R² Score:", r2)

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    'Importance',
    ascending=False
)

display(feature_importance.head(20))

top_features = feature_importance.head(15)

plt.figure(figsize=(10,7))

sns.barplot(
    data=top_features,
    x='Importance',
    y='Feature'
)

plt.title('Top Factors Associated with Yield Prediction')
plt.xlabel('Importance')
plt.ylabel('Feature')

plt.show()

final_summary = df_clean.groupby('Season').agg({

    'Yield_Tonnes_Ha': 'mean',
    'Production_Tonnes': 'mean',
    'Profit_INR': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean',
    'Disease_Pest_Risk_pct': 'mean'

}).round(2)

display(final_summary)

best_yield_season = (
    df_clean.groupby('Season')['Yield_Tonnes_Ha']
    .mean()
    .idxmax()
)

worst_yield_season = (
    df_clean.groupby('Season')['Yield_Tonnes_Ha']
    .mean()
    .idxmin()
)

best_profit_season = (
    df_clean.groupby('Season')['Profit_INR']
    .mean()
    .idxmax()
)

best_water_season = (
    df_clean.groupby('Season')['Water_Efficiency_t_per_1000m3']
    .mean()
    .idxmax()
)

print("Best season based on average yield:", best_yield_season)
print("Lowest season based on average yield:", worst_yield_season)
print("Best season based on average profit:", best_profit_season)
print("Best season based on water efficiency:", best_water_season)

season_stats = df_clean.groupby('Season').agg({
    'Yield_Tonnes_Ha': 'mean',
    'Production_Tonnes': 'mean',
    'Profit_INR': 'mean',
    'Water_Used_m3': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean',
    'Disease_Pest_Risk_pct': 'mean'
})

best_yield = season_stats['Yield_Tonnes_Ha'].idxmax()
best_profit = season_stats['Profit_INR'].idxmax()
best_water = season_stats['Water_Efficiency_t_per_1000m3'].idxmax()
highest_risk = season_stats['Disease_Pest_Risk_pct'].idxmax()

print("========== KEY FINDINGS ==========\n")

print(
    f"1. Highest average yield: {best_yield} "
    f"({season_stats.loc[best_yield, 'Yield_Tonnes_Ha']:.2f} tonnes/ha)"
)

print(
    f"2. Highest average profit: {best_profit} "
    f"(INR {season_stats.loc[best_profit, 'Profit_INR']:,.2f})"
)

print(
    f"3. Highest water efficiency: {best_water} "
    f"({season_stats.loc[best_water, 'Water_Efficiency_t_per_1000m3']:.2f})"
)

print(
    f"4. Highest average disease/pest risk: {highest_risk} "
    f"({season_stats.loc[highest_risk, 'Disease_Pest_Risk_pct']:.2f}%)"
)

print("\n========== SEASON SUMMARY ==========\n")

display(season_stats.round(2))